name: vistiq-env-gpu
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults

dependencies:
  - python=3.12
  - pip
  - setuptools
  - wheel

  # Core scientific/python stack
  - numpy>=1.21
  - pandas>=1.3.1
  - scipy>=1.10
  - scikit-image>=0.18.2
  - matplotlib
  - joblib
  - tifffile

  # dask
  - dask-core>=2022.3.0
  - dask-image>=0.10.0

  # Config / workflow / CLI
  - pydantic>=2.10
  - prefect>=3.0.0
  - typer

  # GPU torch stack
  - pytorch
  - torchvision
  - pytorch-cuda=12.1

  # Imaging / IO
  - bioio>=3.0.0
  - bioio-ome-tiff>=1.4.0
  - micro_sam=1.6.2

  # Prefer conda if it resolves cleanly
  - torch_em

  - pip:
      - -e .
      - bioio-lif>=1.4.1
      - bioio-tifffile>=1.3.0
      - bioio-nd2>=1.5.0
      - napari>=0.6.6
      - napari-animation>=0.0.9
      - opencv-python-headless>=4.12.0
      - stackview>=0.18.0